#!/bin/bash
#Script untuk menghapus user SSH & OpenVPN
clear
read -p "Input user to delete : " Pengguna

if getent passwd $Pengguna > /dev/null 2>&1; then
        userdel $Pengguna
        echo -e "User $Pengguna has been deleted."
else
        echo -e "GAGAL: User $Pengguna does not exist."
fi
