#!/bin/bash
clear
echo "=========================================================="
echo "---------------SSH/VPN Menu by DZEESSH.com----------------"
echo "=========================================================="
	echo ""
	echo -e "-----=[ SSH & OpenVPN Section ]=-----"
	echo -e "$\e[31m1\e[1m.Create User Account"
	echo -e "$\e[31m2\e[1m.Create Trial Account (Hours)"
	echo -e "$\e[31m3\e[1m.Renew User Account"
	echo -e "$\e[31m4\e[1m.Delete User Account"
	echo -e "$\e[31m5\e[1m.Delete All Expired Account"
	echo -e "$\e[31m6\e[1m.Limit Login SSH Account"
	echo -e "$\e[31m7\e[1m.Check Login Account"
	echo -e "$\e[31m8\e[1m.Check Created Account"
	echo -e "$\e[31m9\e[1m.Check Speed Of The Server"
	echo -e "$\e[31m10\e[1m.Restart (Dropbear, OpenSSH, Stunnel4, Squid)"
	echo -e "$\e[31m11\e[1m.Reboot The Server"
	echo -e "-------------------------------------"
	read -p "Choose an option from (1-8): " x
	if test $x -eq 1; then
	buat
	elif test $x -eq 2; then
	renew
	elif test $x -eq 3; then
	clear
	trials
	elif test $x -eq 4; then
	hapus
	elif test $x -eq 5; then
	clear
	delexp
	elif test $x -eq 6; then
	lims
	elif test $x -eq 7; then
	ceks
	elif test $x -eq 8; then
	member
	elif test $x -eq 9; then
	clear
	speedtest
	elif test $x -eq 10; then
	clear
	/etc/init.d/dropbear restart
	/etc/init.d/ssh restart
	/etc/init.d/stunnel4 restart
	/etc/init.d/squid restart
	elif test $x -eq 11; then
	reboot
	else
	echo "Options Not Available In Menu."
	echo " "
	exit
	fi
