#!/bin/bash
clear
echo -e "\e[32m=========================================================="
echo -e "\e[32m---------------\e[96mSSH/VPN Menu by DZEESSH.com\e[32m----------------"
echo -e "\e[32m=========================================================="
	echo ""
	echo -e "\e[32m-----=[ SSH & OpenVPN Section ]=-----"
	echo -e "\e[31m1\e[32m.\e[97mCreate User Account"
	echo -e "\e[31m2\e[32m.\e[97mCreate Trial Account (Hours)"
	echo -e "\e[31m3\e[32m.\e[97mRenew User Account"
	echo -e "\e[31m4\e[32m.\e[97m\e[97mDelete User Account"
	echo -e "\e[31m5\e[32m.\e[97mDelete All Expired Account"
	echo -e "\e[31m6\e[32m.\e[97mLimit Login SSH Account"
	echo -e "\e[31m7\e[32m.\e[97mCheck Login Account"
	echo -e "\e[31m8\e[32m.\e[97mCheck Created Account"
	echo -e "\e[31m9\e[32m.\e[97mCheck Speed Of The Server"
	echo -e "\e[31m10\e[32m.\e[97mRestart (Dropbear, OpenSSH, Stunnel4, Squid)"
	echo -e "\e[31m11\e[32m.\e[97mReboot The Server"
	echo -e "\e[32m-------------------------------------"
	read -p "Choose an option from (1-8): " x
	if test $x -eq 1; then
	buat
	elif test $x -eq 2; then
	renew
	elif test $x -eq 3; then
	clear
	trials
	elif test $x -eq 4; then
	hapus
	elif test $x -eq 5; then
	clear
	delexp
	elif test $x -eq 6; then
	lims
	elif test $x -eq 7; then
	ceks
	elif test $x -eq 8; then
	member
	elif test $x -eq 9; then
	clear
	speedtest
	elif test $x -eq 10; then
	clear
	/etc/init.d/dropbear restart
	/etc/init.d/ssh restart
	/etc/init.d/stunnel4 restart
	/etc/init.d/squid restart
	elif test $x -eq 11; then
	reboot
	else
	echo "Options Not Available In Menu."
	echo " "
	exit
	fi
