#!/bin/bash
clear
echo "--------------- Welcome To Premium Script Menu ---------------"
	echo "--------------- by DZEESSH.com --------------------"
	echo ""
	echo -e "-----=[ SSH & OpenVPN Section ]=-----"
	echo -e "${color1}1${color3}.Create User Account"
	echo -e "${color1}2${color3}.Create Trial Account"
	echo -e "${color1}3${color3}.Delete User Account"
	echo -e "${color1}4${color3}.Delete All Expired Account"
	echo -e "${color1}5${color3}.Check Login Account"
	echo -e "${color1}6${color3}.Check created Account"
	echo -e "${color1}7${color3}.Check speed of the server"
	echo -e "${color1}8${color3}.Restart (Dropbear, OpenSSH, Stunnel4, Squid)"
	echo -e "${color1}9${color3}.Reboot the server"
	echo -e "-------------------------------------"
	read -p "Choose an option from (1-8): " x
	if test $x -eq 1; then
	buat
	elif test $x -eq 2; then
	clear
	trials
	elif test $x -eq 3; then
	hapus
	elif test $x -eq 4; then
	delexp
	elif test $x -eq 5; then
	ceks
	elif test $x -eq 6; then
	member
	elif test $x -eq 7; then
	speedtest
	elif test $x -eq 8; then
	/etc/init.d/dropbear restart
	/etc/init.d/ssh restart
	services stunnel4 restart
	/etc/init.d/squid restart
	elif test $x -eq 9; then
	reboot
	else
	echo "Options Not Available In Menu."
	echo " "
	exit
	fi
