#!/bin/bash
host="$(curl -s icanhazip.com)"
printf -- "------------------SCRIPT TRIAL SSH & OVPN-------------------\n"
sleep 0.5
read -p "Input User     : " user;
read -p "Input Password : " pass;
read -p "Input hours    : " exp;
printf -- "-----MEMERIKSA BINARY AT APAKAH SUDAH DIINSTAL-----\n"
sleep 0.5
if [ -f /usr/bin/at ]
then
printf -- "-------------BINARY TERINSTALL------------\n"
else
printf -- "---BINARY TIDAK DITEMUKAN, MENGINSTALL BINARY---\n" && apt install at -y
fi
sleep 0.5
printf -- "---------------MEMBUAT USER---------------\n"
useradd -N -M -s /bin/false "$user"
sleep 0.5
printf -- "-------------MEMBUAT PASSWORD-------------\n"
echo "$user":"$pass" | chpasswd
sleep 0.5
printf -- "----------MEMBUAT MASA BERLAKU------------\n"
#delete user dan kill semua koneksi
echo "userdel -f $user && pkill -u $user" | at now + "$exp" hours >/dev/null 2>&1
sleep 0.5
printf -- "-----------------SELESAI------------------\n"
sleep 0.5
clear
printf -- "======SSH & OVPN ACCOUNT======\n"
printf -- "Host                  : $host\n"
printf -- "Domain                : *.vip1-id.dzeessh.com\n"
printf -- "WS Dpmain             : sshs.wdcou.tunnelku.my.id\n"
printf -- "Username              : $user\n"
printf -- "Password              : $pass\n"
printf -- "Expired               : $exp Hours\n"
printf -- "------------------------------\n"
printf -- "Port OpenSSH          : 22, 143\n"
printf -- "Port Dropbear         : 444, 445, 446\n\n"
printf -- "Port Stunnel          : 442, 443\n\n"
printf -- "Port Squid            : 8080, 8000\n\n"
printf -- "Port UDPGW            : 7100, 7200, 7300\n"
printf -- "------------------------------\n"
printf -- "Payload SSH Websocket\n"
printf -- "GET / HTTP/1.1[crlf]Host: sshws.wdcou.tunnelku.my.id[crlf]Upgrade: websocket[crlf][crlf]\n"
printf -- "------------------------------\n"
printf -- "OpenVPN TCP (1194)    : http://$host:81/openvpn-tcp.ovpn\n"
printf -- "OpenVPN UDP (1195)    : http://$host:81/openvpn-udp.ovpn\n"
printf -- "OpenVPN SSL (1196)    : http://$host:81/openvpn-tls.ovpn\n\n"
printf -- "=======| Made by DZEESSH |=======\n"
